require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'Spot' do

  # React Native Maps dependencies
  rn_maps_path = '../node_modules/react-native-maps'
  pod 'react-native-google-maps', :path => rn_maps_path
  pod 'GoogleMaps'
  pod 'Google-Maps-iOS-Utils'
  # Add the Firebase pod for Google Analytics
  pod 'Firebase/Analytics'
  pod 'GeoFire/Utils'

    # Add the pods for any other Firebase products you want to use in your app
    # For example, to use Firebase Authentication and Cloud Firestore
    pod 'RNFBFirestore', :path => '../node_modules/@react-native-firebase/firestore'
    pod 'Firebase/Auth'
    pod 'Firebase/Firestore'


  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
  config = use_native_modules!
  use_react_native!(:path => config["reactNativePath"])

  target 'SpotTests' do
    inherit! :complete
    # Pods for testing
  end

end



target 'Spot-tvOS' do
  # Pods for Spot-tvOS

  target 'Spot-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
